import Head from "next/head";
import { useForm } from "react-hook-form";

import { FormValuesProps, Input, Textfield } from "@/components/Input";
import { H1 } from "@/components/Text";

export default function Home() {
  const { register, handleSubmit, watch } = useForm<FormValuesProps>();
  const watchAllFields = watch("소개글");

  const onSubmit = handleSubmit((data) => console.log(data));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <H1 className="text-black">asdfasdfas</H1>
      <form onSubmit={onSubmit}>
        <Input placeholder="asdfasd" label="닉네임" register={register} required />
        <Textfield
          placeholder="asdfasd"
          label="소개글"
          register={register}
          required
          currentLength={watchAllFields?.length ?? 0}
        />
      </form>
    </>
  );
}
